#!/bin/sh
if [ -f /var/mobile/Library/Filza/scripts/oldabichecker.script ]; then
	echo "Removing oldabichecker.script from Filza directory."
	rm /var/mobile/Library/Filza/scripts/oldabichecker.script
fi